# Generated by Django 5.0.14 on 2026-01-05 17:05

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_initial_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    MaintenanceMode = apps.get_model('system', 'MaintenanceMode')
    
    import os
    dev_password = os.getenv('INITIAL_DEVELOPER_PASSWORD', 'developersakiburrahman')
    
    # Create developer user
    User.objects.get_or_create(
        username='developer',
        defaults={
            'role': 'developer',
            'full_name': 'System Developer',
            'password': make_password(dev_password),
            'is_staff': True,
            'is_superuser': True,
            'is_active': True,
        }
    )
    
    # Create default maintenance mode record
    MaintenanceMode.objects.get_or_create(
        id='00000000-0000-0000-0000-000000000001',
        defaults={
            'is_active': False,
            'target_roles': ['student', 'admin'],
            'message': 'System is under maintenance. Please try again later.'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
