# Generated by Django 5.0.14 on 2026-01-08 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_init_developer_and_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('current_page', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'active_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='active_sess_last_ac_e6cf6e_idx'), models.Index(fields=['user'], name='active_sess_user_id_639308_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_attempted', models.CharField(help_text='Username used in login attempt', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('device_model', models.CharField(blank=True, help_text='e.g., iPhone 14 Pro, HP EliteBook 840', max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='e.g., Chrome 120, Safari 17', max_length=100)),
                ('os', models.CharField(blank=True, help_text='e.g., Android 13, Windows 11', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(help_text='Raw user agent string')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='login_logs_timesta_df8393_idx'), models.Index(fields=['ip_address'], name='login_logs_ip_addr_669c36_idx'), models.Index(fields=['status'], name='login_logs_status_c0c84b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Session identifier', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('url_path', models.CharField(help_text='e.g., /dashboard, /tests/123', max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Seconds spent on page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'page_visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='page_visits_timesta_0a3f92_idx'), models.Index(fields=['session_id'], name='page_visits_session_0e311c_idx'), models.Index(fields=['url_path'], name='page_visits_url_pat_65df3b_idx')],
            },
        ),
    ]
